repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: local
  hooks:
    - id: pytest
      name: Run unit tests
      entry: poetry run pytest tests/backend -v
      language: system
      types: [python]
      pass_filenames: false
      always_run: true 